/**
 * The ten Pulse themes.
 *
 * Each entry is a complete semantic color system + metadata. Adding a new
 * theme requires *only* adding an entry here (and nothing else) — the CSS
 * generator, context registry, store and switcher UI are all data-driven.
 */

import type { ThemeConfig, ThemeId } from './types';

export const DEFAULT_THEME_ID: ThemeId = 'dark';

export const THEMES: ThemeConfig[] = [
  /* ── 1. Dark (default) — the current platform theme ──────────────── */
  {
    id: 'dark',
    name: 'Dark',
    description: 'Default dark theme for general use.',
    icon: 'Moon',
    isDark: true,
    category: 'dark',
    previewColors: ['#020617', '#0f172a', '#22d3ee', '#34d399', '#f43f5e'],
    colors: {
      'bg-app': 'slate-950',
      'bg-card': 'slate-900',
      'bg-panel': 'slate-800',
      'bg-hover': 'slate-800/50',
      'bg-active': 'slate-700',
      'text-primary': 'slate-100',
      'text-secondary': 'slate-300',
      'text-tertiary': 'slate-400',
      'text-muted': 'slate-500',
      'text-disabled': 'slate-600',
      'border-subtle': 'slate-700/50',
      'border-default': 'slate-700',
      'border-active': 'slate-600',
      'accent-info': 'cyan-400',
      'accent-info-hover': 'cyan-500',
      'accent-success': 'emerald-400',
      'accent-success-hover': 'emerald-500',
      'accent-warning': 'amber-400',
      'accent-warning-hover': 'amber-500',
      'accent-error': 'rose-500',
      'accent-error-hover': 'rose-600',
      'accent-neutral': 'slate-400',
      'chart-1': 'indigo-500',
      'chart-2': 'cyan-400',
      'chart-3': 'emerald-400',
      'chart-4': 'amber-400',
      'chart-5': 'rose-500',
      'chart-6': 'violet-500',
      'chart-7': 'fuchsia-400',
      'chart-8': 'sky-400',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(0,0,0,0.2), 0 4px 6px -4px rgba(0,0,0,0.2)',
      overlay: 'rgba(15,23,42,0.95)',
      glass: 'rgba(30,41,59,0.6)',
    },
  },

  /* ── 2. Light ─────────────────────────────────────────────────────── */
  {
    id: 'light',
    name: 'Light',
    description: 'Clean light theme for daytime use and presentations.',
    icon: 'Sun',
    isDark: false,
    category: 'light',
    previewColors: ['#f9fafb', '#ffffff', '#3b82f6', '#22c55e', '#ef4444'],
    colors: {
      'bg-app': 'gray-50',
      'bg-card': 'white',
      'bg-panel': 'gray-100',
      'bg-hover': 'gray-100/80',
      'bg-active': 'gray-200',
      'text-primary': 'gray-900',
      'text-secondary': 'gray-700',
      'text-tertiary': 'gray-500',
      'text-muted': 'gray-400',
      'text-disabled': 'gray-300',
      'border-subtle': 'gray-200/80',
      'border-default': 'gray-200',
      'border-active': 'gray-300',
      'accent-info': 'blue-500',
      'accent-info-hover': 'blue-600',
      'accent-success': 'green-500',
      'accent-success-hover': 'green-600',
      'accent-warning': 'orange-500',
      'accent-warning-hover': 'orange-600',
      'accent-error': 'red-500',
      'accent-error-hover': 'red-600',
      'accent-neutral': 'gray-500',
      'chart-1': 'blue-600',
      'chart-2': 'cyan-600',
      'chart-3': 'green-500',
      'chart-4': 'orange-500',
      'chart-5': 'red-500',
      'chart-6': 'purple-600',
      'chart-7': 'pink-500',
      'chart-8': 'sky-600',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(229,231,235,0.5), 0 4px 6px -4px rgba(229,231,235,0.5)',
      overlay: 'rgba(255,255,255,0.95)',
      glass: 'rgba(255,255,255,0.7)',
    },
  },

  /* ── 3. Midnight ──────────────────────────────────────────────────── */
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deeper dark theme with blue undertones for low light.',
    icon: 'MoonStar',
    isDark: true,
    category: 'dark',
    previewColors: ['#0a0a0a', '#171717', '#60a5fa', '#2dd4bf', '#f87171'],
    colors: {
      'bg-app': 'neutral-950',
      'bg-card': 'neutral-900',
      'bg-panel': 'neutral-800',
      'bg-hover': 'neutral-800/60',
      'bg-active': 'neutral-700',
      'text-primary': 'neutral-100',
      'text-secondary': 'neutral-300',
      'text-tertiary': 'neutral-400',
      'text-muted': 'neutral-500',
      'text-disabled': 'neutral-600',
      'border-subtle': 'neutral-700/50',
      'border-default': 'neutral-700',
      'border-active': 'neutral-600',
      'accent-info': 'blue-400',
      'accent-info-hover': 'blue-500',
      'accent-success': 'teal-400',
      'accent-success-hover': 'teal-500',
      'accent-warning': 'yellow-400',
      'accent-warning-hover': 'yellow-500',
      'accent-error': 'red-400',
      'accent-error-hover': 'red-500',
      'accent-neutral': 'neutral-400',
      'chart-1': 'blue-500',
      'chart-2': 'cyan-500',
      'chart-3': 'teal-400',
      'chart-4': 'yellow-400',
      'chart-5': 'red-400',
      'chart-6': 'indigo-400',
      'chart-7': 'purple-400',
      'chart-8': 'sky-400',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(0,0,0,0.3), 0 4px 6px -4px rgba(0,0,0,0.3)',
      overlay: 'rgba(23,23,23,0.95)',
      glass: 'rgba(38,38,38,0.6)',
    },
  },

  /* ── 4. Ocean ─────────────────────────────────────────────────────── */
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Calming blue-green theme for long monitoring sessions.',
    icon: 'Waves',
    isDark: true,
    category: 'colorful',
    previewColors: ['#042f2e', '#134e4a', '#67e8f9', '#86efac', '#fda4af'],
    colors: {
      'bg-app': 'teal-950',
      'bg-card': 'teal-900',
      'bg-panel': 'teal-800',
      'bg-hover': 'teal-800/50',
      'bg-active': 'teal-700',
      'text-primary': 'teal-50',
      'text-secondary': 'teal-200',
      'text-tertiary': 'teal-300',
      'text-muted': 'teal-400',
      'text-disabled': 'teal-500',
      'border-subtle': 'teal-700/50',
      'border-default': 'teal-700',
      'border-active': 'teal-600',
      'accent-info': 'cyan-300',
      'accent-info-hover': 'cyan-400',
      'accent-success': 'green-300',
      'accent-success-hover': 'green-400',
      'accent-warning': 'amber-300',
      'accent-warning-hover': 'amber-400',
      'accent-error': 'rose-300',
      'accent-error-hover': 'rose-400',
      'accent-neutral': 'teal-300',
      'chart-1': 'cyan-400',
      'chart-2': 'teal-300',
      'chart-3': 'green-300',
      'chart-4': 'amber-300',
      'chart-5': 'rose-300',
      'chart-6': 'blue-300',
      'chart-7': 'indigo-300',
      'chart-8': 'sky-300',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(4,47,46,0.4), 0 4px 6px -4px rgba(4,47,46,0.4)',
      overlay: 'rgba(19,78,74,0.95)',
      glass: 'rgba(17,94,89,0.6)',
    },
  },

  /* ── 5. Forest ────────────────────────────────────────────────────── */
  {
    id: 'forest',
    name: 'Forest',
    description: 'Natural green theme for health and environmental monitoring.',
    icon: 'TreePine',
    isDark: true,
    category: 'colorful',
    previewColors: ['#052e16', '#14532d', '#6ee7b7', '#bef264', '#fca5a5'],
    colors: {
      'bg-app': 'green-950',
      'bg-card': 'green-900',
      'bg-panel': 'green-800',
      'bg-hover': 'green-800/50',
      'bg-active': 'green-700',
      'text-primary': 'green-50',
      'text-secondary': 'green-200',
      'text-tertiary': 'green-300',
      'text-muted': 'green-400',
      'text-disabled': 'green-500',
      'border-subtle': 'green-700/50',
      'border-default': 'green-700',
      'border-active': 'green-600',
      'accent-info': 'emerald-300',
      'accent-info-hover': 'emerald-400',
      'accent-success': 'lime-300',
      'accent-success-hover': 'lime-400',
      'accent-warning': 'yellow-300',
      'accent-warning-hover': 'yellow-400',
      'accent-error': 'red-300',
      'accent-error-hover': 'red-400',
      'accent-neutral': 'green-300',
      'chart-1': 'emerald-400',
      'chart-2': 'green-300',
      'chart-3': 'lime-300',
      'chart-4': 'yellow-300',
      'chart-5': 'red-300',
      'chart-6': 'teal-300',
      'chart-7': 'cyan-300',
      'chart-8': 'sky-300',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(5,46,22,0.4), 0 4px 6px -4px rgba(5,46,22,0.4)',
      overlay: 'rgba(20,83,45,0.95)',
      glass: 'rgba(22,101,52,0.6)',
    },
  },

  /* ── 6. Sunset ────────────────────────────────────────────────────── */
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm orange-red theme for evening shifts and alerts.',
    icon: 'Sunset',
    isDark: true,
    category: 'colorful',
    previewColors: ['#431407', '#7c2d12', '#fcd34d', '#fdba74', '#f87171'],
    colors: {
      'bg-app': 'orange-950',
      'bg-card': 'orange-900',
      'bg-panel': 'orange-800',
      'bg-hover': 'orange-800/50',
      'bg-active': 'orange-700',
      'text-primary': 'orange-50',
      'text-secondary': 'orange-200',
      'text-tertiary': 'orange-300',
      'text-muted': 'orange-400',
      'text-disabled': 'orange-500',
      'border-subtle': 'orange-700/50',
      'border-default': 'orange-700',
      'border-active': 'orange-600',
      'accent-info': 'amber-300',
      'accent-info-hover': 'amber-400',
      'accent-success': 'green-300',
      'accent-success-hover': 'green-400',
      'accent-warning': 'yellow-300',
      'accent-warning-hover': 'yellow-400',
      'accent-error': 'red-400',
      'accent-error-hover': 'red-500',
      'accent-neutral': 'orange-300',
      'chart-1': 'amber-400',
      'chart-2': 'orange-300',
      'chart-3': 'red-300',
      'chart-4': 'yellow-300',
      'chart-5': 'rose-300',
      'chart-6': 'pink-300',
      'chart-7': 'purple-300',
      'chart-8': 'blue-300',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(67,20,7,0.4), 0 4px 6px -4px rgba(67,20,7,0.4)',
      overlay: 'rgba(124,45,18,0.95)',
      glass: 'rgba(154,52,18,0.6)',
    },
  },

  /* ── 7. Lavender ──────────────────────────────────────────────────── */
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft purple theme for creative and design-focused teams.',
    icon: 'Flower2',
    isDark: true,
    category: 'colorful',
    previewColors: ['#2e1065', '#4c1d95', '#d8b4fe', '#f0abfc', '#fda4af'],
    colors: {
      'bg-app': 'violet-950',
      'bg-card': 'violet-900',
      'bg-panel': 'violet-800',
      'bg-hover': 'violet-800/50',
      'bg-active': 'violet-700',
      'text-primary': 'violet-50',
      'text-secondary': 'violet-200',
      'text-tertiary': 'violet-300',
      'text-muted': 'violet-400',
      'text-disabled': 'violet-500',
      'border-subtle': 'violet-700/50',
      'border-default': 'violet-700',
      'border-active': 'violet-600',
      'accent-info': 'purple-300',
      'accent-info-hover': 'purple-400',
      'accent-success': 'fuchsia-300',
      'accent-success-hover': 'fuchsia-400',
      'accent-warning': 'amber-300',
      'accent-warning-hover': 'amber-400',
      'accent-error': 'rose-300',
      'accent-error-hover': 'rose-400',
      'accent-neutral': 'violet-300',
      'chart-1': 'purple-400',
      'chart-2': 'violet-300',
      'chart-3': 'fuchsia-300',
      'chart-4': 'pink-300',
      'chart-5': 'rose-300',
      'chart-6': 'indigo-300',
      'chart-7': 'blue-300',
      'chart-8': 'cyan-300',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(46,16,101,0.4), 0 4px 6px -4px rgba(46,16,101,0.4)',
      overlay: 'rgba(76,29,149,0.95)',
      glass: 'rgba(91,33,182,0.6)',
    },
  },

  /* ── 8. Monochrome ────────────────────────────────────────────────── */
  {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'High-contrast black & white for projection screens.',
    icon: 'Contrast',
    isDark: true,
    category: 'accessibility',
    previewColors: ['#000000', '#171717', '#ffffff', '#d4d4d4', '#737373'],
    colors: {
      'bg-app': 'black',
      'bg-card': 'neutral-900',
      'bg-panel': 'neutral-800',
      'bg-hover': 'neutral-800/70',
      'bg-active': 'neutral-700',
      'text-primary': 'white',
      'text-secondary': 'neutral-300',
      'text-tertiary': 'neutral-400',
      'text-muted': 'neutral-500',
      'text-disabled': 'neutral-600',
      'border-subtle': 'neutral-700/70',
      'border-default': 'neutral-700',
      'border-active': 'neutral-500',
      'accent-info': 'white',
      'accent-info-hover': 'neutral-200',
      'accent-success': 'neutral-300',
      'accent-success-hover': 'neutral-400',
      'accent-warning': 'neutral-400',
      'accent-warning-hover': 'neutral-500',
      'accent-error': 'neutral-500',
      'accent-error-hover': 'neutral-600',
      'accent-neutral': 'neutral-400',
      'chart-1': 'white',
      'chart-2': 'neutral-300',
      'chart-3': 'neutral-400',
      'chart-4': 'neutral-500',
      'chart-5': 'neutral-600',
      'chart-6': 'neutral-200',
      'chart-7': 'neutral-700',
      'chart-8': 'neutral-100',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(0,0,0,0.5), 0 4px 6px -4px rgba(0,0,0,0.5)',
      overlay: 'rgba(0,0,0,0.95)',
      glass: 'rgba(38,38,38,0.7)',
    },
  },

  /* ── 9. High Contrast ─────────────────────────────────────────────── */
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Maximum contrast for vision impairments and outdoor use.',
    icon: 'Eye',
    isDark: true,
    category: 'accessibility',
    previewColors: ['#000000', '#0a0a0a', '#67e8f9', '#4ade80', '#facc15'],
    colors: {
      'bg-app': 'black',
      'bg-card': 'black',
      'bg-panel': 'neutral-900',
      'bg-hover': 'neutral-900',
      'bg-active': 'neutral-800',
      'text-primary': 'white',
      'text-secondary': 'white',
      'text-tertiary': 'neutral-300',
      'text-muted': 'neutral-400',
      'text-disabled': 'neutral-600',
      'border-subtle': 'white/30',
      'border-default': 'white/50',
      'border-active': 'white',
      'accent-info': 'cyan-300',
      'accent-info-hover': 'cyan-400',
      'accent-success': 'green-400',
      'accent-success-hover': 'green-500',
      'accent-warning': 'yellow-400',
      'accent-warning-hover': 'yellow-500',
      'accent-error': 'red-400',
      'accent-error-hover': 'red-500',
      'accent-neutral': 'white',
      'chart-1': 'cyan-400',
      'chart-2': 'green-400',
      'chart-3': 'yellow-400',
      'chart-4': 'red-400',
      'chart-5': 'blue-400',
      'chart-6': 'purple-400',
      'chart-7': 'orange-400',
      'chart-8': 'pink-400',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.5)',
      overlay: 'rgba(0,0,0,0.98)',
      glass: 'rgba(23,23,23,0.8)',
    },
  },

  /* ── 10. Terminal ─────────────────────────────────────────────────── */
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Retro green-on-black terminal aesthetic for developers.',
    icon: 'Terminal',
    isDark: true,
    category: 'specialty',
    previewColors: ['#000000', '#052e16', '#4ade80', '#86efac', '#facc15'],
    colors: {
      'bg-app': 'black',
      'bg-card': 'black',
      'bg-panel': 'green-950',
      'bg-hover': 'green-900/50',
      'bg-active': 'green-900',
      'text-primary': 'green-400',
      'text-secondary': 'green-500',
      'text-tertiary': 'green-600',
      'text-muted': 'green-700',
      'text-disabled': 'green-800',
      'border-subtle': 'green-800/50',
      'border-default': 'green-800',
      'border-active': 'green-600',
      'accent-info': 'green-300',
      'accent-info-hover': 'green-400',
      'accent-success': 'green-400',
      'accent-success-hover': 'green-500',
      'accent-warning': 'yellow-400',
      'accent-warning-hover': 'yellow-500',
      'accent-error': 'red-400',
      'accent-error-hover': 'red-500',
      'accent-neutral': 'green-500',
      'chart-1': 'green-400',
      'chart-2': 'green-300',
      'chart-3': 'green-500',
      'chart-4': 'green-200',
      'chart-5': 'yellow-400',
      'chart-6': 'red-400',
      'chart-7': 'cyan-400',
      'chart-8': 'emerald-400',
    },
    surfaces: {
      elevated: '0 10px 15px -3px rgba(20,83,45,0.3), 0 0 0 1px #166534',
      overlay: 'rgba(0,0,0,0.98)',
      glass: 'rgba(5,46,22,0.7)',
    },
  },
];

export const THEME_MAP: Record<ThemeId, ThemeConfig> = THEMES.reduce(
  (acc, t) => {
    acc[t.id] = t;
    return acc;
  },
  {} as Record<ThemeId, ThemeConfig>,
);

export const THEME_IDS: ThemeId[] = THEMES.map((t) => t.id);

export function isThemeId(value: string | null | undefined): value is ThemeId {
  return !!value && THEME_IDS.includes(value as ThemeId);
}
